# Generated by Django 5.2.17 on 2026-09-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmember',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
